brew "zinit"
brew "oh-my-posh", args: ["--build-from-source"]
brew "jq"
brew "eza"
brew "zoxide"
brew "fzf"
brew "ripgrep"
brew "tokei"
brew "dust"
brew "fastfetch"
brew "inxi"
brew "yazi"
brew "cyme"
